name: stanalysis
version: 1.0.0
description: Opinionated static analyzer rule set to keep a Dart codebase maintainable.
repository: https://github.com/Pavel-Sulimau/stanalysis

environment:
  sdk: ">=2.18.0 <4.0.0"
