name: stanalysis
version: 1.0.0
description: Static analyzer settings to keep a codebase Dart code maintainable.
repository: https://github.com/Pavel-Sulimau/stanalysis

environment:
  sdk: ">=2.18.0 <3.0.0"
